#!/bin/bash -e
# Check for updates in the spotify deb package

# Get the current dir, as we want to store the ebuild here
CURDIR=$(pwd)

# Get the dir where we have our stuff
SCRIPTDIR="$(dirname $(readlink -f $0))"

# Fetch the index.html from the repository
INDEX_HTML=$(curl -s http://repository.spotify.com/pool/non-free/s/spotify/)

# Do some sed/awk magic to get the available files
# the sed line catches any spotify-client*.deb in the index.html
# the awk line makes sure we don't do double work
FILES=$(echo "$INDEX_HTML" |
	sed -n "s/.*a href=\"spotify-client-qt_\(.*\)\_.*\.deb\".*/\1/p" |
	awk '!x[$0]++')

for FILE in $FILES
do
	# file name format is something like
	# spotify-client-qt_0.6.2.291.gcccc1f5.116-1_amd64.deb
	# the interesting parts for ebuilds would be
	# 0.6.2.291 as part of the ebuild name (version)
	# gcccc1f5.116-1 for in the ebuild. It's unfortunately
	# necessary to add it at this point.

	# pull out version info
	VERSION=$(echo $FILE | sed -n "s/^\(\([0-9]\.\)\+[0-9]*\).*/\1/p")

	MYPV=$(echo $FILE | sed -n "s/^[0-9\.]*\(g.*\)/\1/p")

	EBUILD_TEMPLATE=$(cat ${SCRIPTDIR}/ebuild_template)
	EBUILD_NAME="${CURDIR}/spotify-$VERSION.ebuild"

	echo "$EBUILD_TEMPLATE" | sed "s/TEMPLATE_MYPV/$MYPV/g" > $EBUILD_NAME
	echo "Created new ebuild: $EBUILD_NAME"

	# Build the manifest
	ebuild "${EBUILD_NAME}" manifest
done
