#!/bin/bash -e

# Check for updates in the spotify deb package

INDEX_HTML=$(curl -s http://repository.spotify.com/pool/non-free/s/spotify/)
echo "$INDEX_HTML" | sed -n "s/.*a href=\"\(spotify-client.*\.deb\)\".*/\1/p"
